version: '3'

volumes:
  db_data:

services:
  db:
    image: postgres:11.1
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    image: schmiedeone/audit-app-backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
